# Generated by Django 4.2.26 on 2025-11-30 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accesscontrolentry",
            old_name="can_delete",
            new_name="can_execute",
        ),
        migrations.RemoveField(
            model_name="accesscontrolentry",
            name="can_share",
        ),
    ]
