# Generated by Django 4.2.26 on 2025-12-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_can_delete_accesscontrolentry_can_execute_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="accesscontrolentry",
            name="user_or_organization_not_both",
        ),
        migrations.AddConstraint(
            model_name="accesscontrolentry",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("organization__isnull", False), ("user__isnull", False)
                ),
                name="user_or_organization_required",
            ),
        ),
    ]
