# Generated by Django 4.2.26 on 2025-12-01 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_remove_accesscontrolentry_user_or_organization_not_both_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="AccessControlEntry",
        ),
    ]
