# Generated by Django 4.2.26 on 2025-12-01 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_delete_accesscontrolentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_organizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
