# Generated by Django 4.2.26 on 2025-12-04 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_organization_manager"),
    ]

    operations = [
    migrations.CreateModel(
        name="Bucket",
        fields=[
            ("id", models.BigAutoField(primary_key=True, auto_created=True, serialize=False, verbose_name="ID")),
            ("name", models.CharField(max_length=255)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
            ("updated_at", models.DateTimeField(auto_now=True)),
            ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="buckets", to="accounts.organization")),
        ],
        options={"db_table": "buckets"},
    ),
    migrations.AddIndex(
        model_name="bucket",
        index=models.Index(fields=["name"], name="buckets_name_f837aa_idx"),
    ),
    migrations.AddIndex(
        model_name="bucket",
        index=models.Index(fields=["organization", "created_at"], name="buckets_organiz_c4f120_idx"),
    ),
    migrations.AddConstraint(
        model_name="bucket",
        constraint=models.UniqueConstraint(fields=("name", "organization"), name="unique_bucket_name_per_org"),
    ),
]

